# Generated by Django 3.2.10 on 2024-03-26 21:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='expire',
            field=models.DurationField(default=datetime.timedelta(seconds=300)),
        ),
    ]
